### ISSUE TITLE
Feature: Allow HTML source view for HTML editor

### ISSUE THREAD

**Issue by cluetjen** [heavendata/issues#2]
Currently, there's only the wysiwyg view available but for some edits we need to manually "fix" the html source code.

Feature request: Add raw html view

**Comment by AnnaTkachenko** [comment]
Now html source view is available for wysiwyg editor:
![image](https://user-images.githubusercontent.com/26151759/115401098-4fe8ad00-a1ea-11eb-93ab-a55af6a8836b.png)
![image](https://user-images.githubusercontent.com/26151759/115401141-5d9e3280-a1ea-11eb-8702-427391864d39.png)

And I did add more features for the editor:
- Strikethrough
- Subscript
- Superscript
- Table tools
